### ISSUE TITLE
Custom recipes do not work on the server

### ISSUE THREAD

**Issue by yottybyte** [GregTechCEu/GregTech-Community-Pack#110]
Some recipes, such as basic drawer or drawer controller and some others, do not work on the server.
JEI will display the changed recipe, and when crafting, only the one that was before the change works

The server starts with java version 1.8.0_382
os: debian

<img width="238" alt="Снимок экрана 2023-10-16 в 14 17 56" src="https://github.com/GregTechCEu/GregTech-Community-Pack/assets/39698457/dcff1738-70a2-4391-b5cb-c8161d4b1391">
<img width="234" alt="Снимок экрана 2023-10-16 в 14 18 07" src="https://github.com/GregTechCEu/GregTech-Community-Pack/assets/39698457/a1de3684-cf0e-41bc-a9b2-ea6c3d4fb521">

**Comment by yottybyte** [comment]
groovy log

`
============  GroovyLog  ====  16.10.2023  ============
GroovyScript version: 0.6.4
[14:14:54] [SERVER/INFO] [groovyscript]: Running scripts in loader 'preInit'
[14:14:56] [SERVER/INFO] [groovyscript]:  - executing classes/MetaTileEntityGreenhouse.groovy
[14:14:56] [SERVER/INFO] [groovyscript]:  - executing classes/globals.groovy
[14:14:56] [SERVER/INFO] [groovyscript]:  - executing preInit/materials.groovy
[14:15:04] [SERVER/INFO] [groovyscript]: Running scripts in loader 'init'
[14:15:04] [SERVER/INFO] [groovyscript]:  - executing classes/MetaTileEntityGreenhouse.groovy
[14:15:04] [SERVER/INFO] [groovyscript]:  - executing classes/globals.groovy
[14:15:04] [SERVER/INFO] [groovyscript]: Running scripts in loader 'postInit'
[14:15:04] [SERVER/INFO] [groovyscript]:  - executing classes/MetaTileEntityGreenhouse.groovy
[14:15:05] [SERVER/INFO] [groovyscript]:  - executing classes/globals.groovy
[14:15:05] [SERVER/INFO] [groovyscript]:  - executing postInit/machines.groovy
[14:15:05] [SERVER/INFO] [groovyscript]:  - executing postInit/oredicts.groovy
[14:15:05] [SERVER/INFO] [groovyscript]:  - executing postInit/ae2.groovy
[14:15:05] [SERVER/ERROR] [groovyscript]: An exception occurred while running scripts. Look at latest.log for a full stacktrace:
	java.lang.TypeNotPresentException: Type net.minecraftforge.fml.client.config.GuiConfigEntries$IConfigEntry not present
		at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
		at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
		at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
		at sun.reflect.generics.reflectiveObjects.WildcardTypeImpl.getUpperBounds(WildcardTypeImpl.java:130)
		at com.sun.beans.TypeResolver.resolve(TypeResolver.java:175)
		at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
		at com.sun.beans.TypeResolver.resolve(TypeResolver.java:169)
		at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
		at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96)
		at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
		at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
		at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
		at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
		at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1205)
		at java.beans.Introspector.getBeanInfo(Introspector.java:426)
		at java.beans.Introspector.getBeanInfo(Introspector.java:173)
		at java.beans.Introspector.getBeanInfo(Introspector.java:260)
		at java.beans.Introspector.<init>(Introspector.java:407)
		at java.beans.Introspector.getBeanInfo(Introspector.java:173)
		at groovy.lang.MetaClassImpl.lambda$addProperties$25(MetaClassImpl.java:3465)
		at java.security.AccessController.doPrivileged(Native Method)
		at groovy.lang.MetaClassImpl.doPrivileged(MetaClassImpl.java:3497)
		at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3465)
		at groovy.lang.MetaClassImpl.reinitialize(MetaClassImpl.java:3447)
		at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3440)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:272)
		at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:314)
		in ae2.groovy in line 1231
		at com.cleanroommc.groovyscript.sandbox.GroovySandbox.loadScripts(GroovySandbox.java:121)

`

**Comment by yottybyte** [comment]
I think I found the error in the file ae2.groovy
Please fix this

`def final hasChannels = AEConfig.instance().isFeatureEnabled(AEFeature.CHANNELS)`

<img width="713" alt="Снимок экрана 2023-10-16 в 14 42 48" src="https://github.com/GregTechCEu/GregTech-Community-Pack/assets/39698457/cb736a0f-460e-423a-a48c-2e9ee812abae">

**Comment by htmlcsjs** [comment]
fixed in f6cd9d01ae484ade0d38d93257f5acbf0b29630a
