### ISSUE TITLE
LoliASM causing strange crash

### ISSUE THREAD

**Issue by Kaio-Cesar** [GregTechCEu/GregTech-Community-Pack#48]
I really don't know how it happened, was some time ago, if I recall, I was using p2p tunnels on a big network.
I know my modpack is slightly off from the official version (some mods added up), but, removing loliASM fixed it, didn't try putting it back after.

Crash Report:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022-04-29 18:02:02 BRT
Description: Exception in server tick loop

java.lang.NullPointerException
    at appeng.crafting.CraftingLinkNexus.isDead(CraftingLinkNexus.java:56)
    at appeng.me.cache.CraftingGridCache.onUpdateTick(CraftingGridCache.java:152)
    at appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:43)
    at appeng.me.Grid.update(Grid.java:278)
    at appeng.hooks.TickHandler.onTick(TickHandler.java:223)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_726_TickHandler_onTick_TickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:712)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_265, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
  Memory: 2527178240 bytes (2410 MB) / 3617587200 bytes (3450 MB) up to 7516192768 bytes (7168 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx8064m
  IntCache: cache: 2, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 LoliASM 4.4 Powered by Forge 14.23.5.2860 109 mods loaded, 109 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                   | Version                            | Source                                                     | Signature                                |
       |:------ |:------------------------------------ |:---------------------------------- |:---------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                            | 1.12.2                             | minecraft.jar                                              | None                                     |
       | LCHIJA | mcp                                  | 9.42                               | minecraft.jar                                              | None                                     |
       | LCHIJA | FML                                  | 8.0.99.99                          | forge-1.12.2-14.23.5.2860-universal.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                | 14.23.5.2860                       | forge-1.12.2-14.23.5.2860-universal.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy                    | 1.0.0                              | minecraft.jar                                              | None                                     |
       | LCHIJA | littletilescore                      | 1.0.0                              | minecraft.jar                                              | None                                     |
       | LCHIJA | xaerominimap_core                    | 1.12.2-1.0                         | minecraft.jar                                              | None                                     |
       | LCHIJA | xaeroworldmap_core                   | 1.12.2-1.0                         | minecraft.jar                                              | None                                     |
       | LCHIJA | foamfixcore                          | 7.7.4                              | minecraft.jar                                              | None                                     |
       | LCHIJA | opencomputers|core                   | 1.7.5.192                          | minecraft.jar                                              | None                                     |
       | LCHIJA | moresoundconfigcore                  | 1.0.0                              | minecraft.jar                                              | None                                     |
       | LCHIJA | randompatches                        | 1.12.2-1.22.1.10                   | randompatches-1.12.2-1.22.1.10.jar                         | None                                     |
       | LCHIJA | ctm                                  | MC1.12.2-1.0.2.31                  | CTM-MC1.12.2-1.0.2.31.jar                                  | None                                     |
       | LCHIJA | appliedenergistics2                  | rv6-stable-7-extended_life-v0.52.2 | appliedenergistics2-rv6-stable-7-extended_life-v0.52.2.jar | None                                     |
       | LCHIJA | baubles                              | 1.5.2                              | Baubles-1.12-1.5.2.jar                                     | None                                     |
       | LCHIJA | p455w0rdslib                         | 2.3.161                            | p455w0rdslib-1.12.2-2.3.161.jar                            | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | ae2wtlib                             | 1.0.34                             | AE2WTLib-1.12.2-1.0.34.jar                                 | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | aiimprovements                       | 0.0.1.1                            | AIImprovements-1.12.1-0.0.1b1.jar                          | None                                     |
       | LCHIJA | crafttweaker                         | 4.1.20                             | CraftTweaker2-1.12-4.1.20.662.jar                          | None                                     |
       | LCHIJA | mtlib                                | 3.0.7                              | MTLib-3.0.7.jar                                            | None                                     |
       | LCHIJA | modtweaker                           | 4.0.19                             | modtweaker-4.0.20.5.jar                                    | None                                     |
       | LCHIJA | jei                                  | 4.16.1                             | HadEnoughItems_1.12.2-4.16.1.jar                           | None                                     |
       | LCHIJA | appleskin                            | 1.0.14                             | AppleSkin-mc1.12-1.0.14.jar                                | None                                     |
       | LCHIJA | attributefix                         | 1.0.10                             | AttributeFix-1.12.2-1.0.10.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | badwithernocookiereloaded            | 1.12.2-3.4.18                      | badwithernocookiereloaded-1.12.2-3.4.18.jar                | None                                     |
       | LCHIJA | betteradvancements                   | 0.1.0.77                           | BetterAdvancements-1.12.2-0.1.0.77.jar                     | None                                     |
       | LCHIJA | betterbedrockgen                     | 6.0.2                              | BetterBedrockGenerator-1.12-6.1.1.jar                      | None                                     |
       | LCHIJA | betterbuilderswands                  | 0.13.2                             | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar          | None                                     |
       | LCHIJA | betterquesting                       | 3.5.329                            | BetterQuesting-3.5.329.jar                                 | None                                     |
       | LCHIJA | bqtweaker                            | 1.3.2                              | BQTweaker-1.3.2.jar                                        | None                                     |
       | LCHIJA | buildinggadgets                      | 2.8.4                              | BuildingGadgets-2.8.4.jar                                  | None                                     |
       | LCHIJA | carryon                              | 1.12.3                             | carryon-1.12.2-1.12.6.20.jar                               | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCHIJA | chameleon                            | 1.12-4.1.3                         | Chameleon-1.12-4.1.3.jar                                   | None                                     |
       | LCHIJA | chesttransporter                     | 2.8.8                              | ChestTransporter-1.12.2-2.8.8.jar                          | None                                     |
       | LCHIJA | chisel                               | MC1.12.2-1.0.2.45                  | Chisel-MC1.12.2-1.0.2.45.jar                               | None                                     |
       | LCHIJA | clienttweaks                         | 3.1.11                             | ClientTweaks_1.12.2-3.1.11.jar                             | None                                     |
       | LCHIJA | clumps                               | 3.1.2                              | Clumps-3.1.2.jar                                           | None                                     |
       | LCHIJA | codechickenlib                       | 3.2.3.358                          | CodeChickenLib-1.12.2-3.2.3.358-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | controlling                          | 3.0.10                             | Controlling-3.0.10.jar                                     | None                                     |
       | LCHIJA | cosmeticarmorreworked                | 1.12.2-v5a                         | CosmeticArmorReworked-1.12.2-v5a.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | craftingtweaks                       | 8.1.9                              | CraftingTweaks_1.12.2-8.1.9.jar                            | None                                     |
       | LCHIJA | ctgui                                | 1.0.0                              | CraftTweaker2-1.12-4.1.20.662.jar                          | None                                     |
       | LCHIJA | crafttweakerjei                      | 2.0.3                              | CraftTweaker2-1.12-4.1.20.662.jar                          | None                                     |
       | LCHIJA | creativecore                         | 1.10.0                             | CreativeCore_v1.10.69_mc1.12.2.jar                         | None                                     |
       | LCHIJA | stg                                  | 1.12.2-1.2.3                       | stg-1.12.2-1.2.3.jar                                       | None                                     |
       | LCHIJA | theoneprobe                          | 1.4.28                             | theoneprobe-1.12-1.4.28.jar                                | None                                     |
       | LCHIJA | mousetweaks                          | 3.1.1                              | MouseTweaks-3.1.1-mc1.12.2.jar                             | None                                     |
       | LCHIJA | danknull                             | 1.7.91                             | DankNull-1.12.2-1.7.91.jar                                 | 644f38521a349310a5dae0239577dc7beebefaec |
       | LCHIJA | diethopper                           | 1.1                                | diethopper-1.1.jar                                         | None                                     |
       | LCHIJA | ding                                 | 1.0.2                              | Ding-1.12.2-1.0.2.jar                                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | dynamistics                          | 1.0.2                              | dynamistics-1.0.2.jar                                      | None                                     |
       | LCHIJA | elevatorid                           | 1.3.14                             | ElevatorMod-1.12.2-1.3.14.jar                              | None                                     |
       | LCHIJA | enchdesc                             | 1.1.20                             | EnchantmentDescriptions-1.12.2-1.1.20.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | fastfurnace                          | 1.3.1                              | FastFurnace-1.12.2-1.3.1.jar                               | None                                     |
       | LCHIJA | fastbench                            | 1.7.3                              | FastWorkbench-1.12.2-1.7.3.jar                             | None                                     |
       | LCHIJA | featuredservers                      | 1.12-1.0.6                         | FeaturedServers-1.12-1.0.6.jar                             | None                                     |
       | LCHIJA | findme                               | 1.0.0                              | findme-1.12.2-1.0.0.jar                                    | None                                     |
       | LCHIJA | foamfix                              | 0.10.14-1.12.2                     | foamfix-0.10.14-1.12.2.jar                                 | None                                     |
       | LCHIJA | forgelin                             | 1.8.3                              | Forgelin-1.8.3.jar                                         | None                                     |
       | LCHIJA | storagedrawers                       | 5.2.2                              | StorageDrawers-1.12.2-5.4.2.jar                            | None                                     |
       | LCHIJA | framedcompactdrawers                 | 1.2.7                              | framedcompactdrawers-1.2.7.jar                             | None                                     |
       | LCHIJA | ftbultimine                          | 1202.3.5                           | ftb-ultimine-1202.3.5.jar                                  | None                                     |
       | LCHIJA | ftbbackups                           | 1.1.0.1                            | FTBBackups-1.1.0.1.jar                                     | None                                     |
       | LCHIJA | ftblib                               | 5.4.7.2                            | FTBLib-5.4.7.2.jar                                         | None                                     |
       | LCHIJA | ftbutilities                         | 5.4.1.131                          | FTBUtilities-5.4.1.131.jar                                 | None                                     |
       | LCHIJA | gregtech                             | 2.2.1-beta                         | gregtech-1.12.2-2.2.1-beta.jar                             | None                                     |
       | LCHIJA | harvest                              | 1.12-1.2.8-25                      | Harvest-1.12-1.2.8-25.jar                                  | None                                     |
       | LCHIJA | incontrol                            | 3.9.18                             | incontrol-1.12-3.9.18.jar                                  | None                                     |
       | LCHIJA | lunatriuscore                        | 1.2.0.42                           | LunatriusCore-1.12.2-1.2.0.42-universal.jar                | None                                     |
       | LCHIJA | ingameinfoxml                        | 2.8.2.94                           | InGameInfoXML-1.12.2-2.8.2.94-universal.jar                | None                                     |
       | LCHIJA | inventorytweaks                      | 1.64+dev.151.822d839               | InventoryTweaks-1.64+dev.151.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks                        | 1.12.2-3.0.8-12                    | IronBackpacks-1.12.2-3.0.8-12.jar                          | None                                     |
       | LCHIJA | jeiintegration                       | 1.6.0                              | jeiintegration_1.12.2-1.6.0.jar                            | None                                     |
       | LCHIJA | littletiles                          | 1.5.0                              | LittleTiles_v1.5.49_mc1.12.2.jar                           | None                                     |
       | LCHIJA | mixinbooter                          | 2.0                                | mixinbooter-2.0.jar                                        | None                                     |
       | LCHIJA | spark                                | 1.5.2                              | spark-forge1122.jar                                        | None                                     |
       | LCHIJA | loliasm                              | 4.4                                | loliasm-4.4.jar                                            | None                                     |
       | LCHIJA | modnametooltip                       | 1.10.1                             | modnametooltip_1.12.2-1.10.1.jar                           | None                                     |
       | LCHIJA | moreoverlays                         | 1.15.1                             | moreoverlays-1.15.1-mc1.12.2.jar                           | None                                     |
       | LCHIJA | multiblocktweaker                    | 1.12.2-stable-gtceu-1.7.0          | multiblocktweaker-1.12.2-stable-gtceu-1.7.0.jar            | None                                     |
       | LCHIJA | naturescompass                       | 1.8.5                              | NaturesCompass-1.12.2-1.8.5.jar                            | None                                     |
       | LCHIJA | netherportalfix                      | 5.3.17                             | NetherPortalFix_1.12.1-5.3.17.jar                          | None                                     |
       | LCHIJA | nuclearcraft                         | 2.18zz                             | NuclearCraft-2.18zz-1.12.2.jar                             | None                                     |
       | LCHIJA | oauth                                | ${version}                         | oauth-1.06.1-1.12.jar                                      | None                                     |
       | LCHIJA | opencomputers                        | 1.7.5.192                          | OpenComputers-MC1.12.2-1.7.5.192.jar                       | None                                     |
       | LCHIJA | openglider                           | @VERSION@                          | OpenGlider-1.12.1-1.1.0.jar                                | None                                     |
       | LCHIJA | overpoweredarmorbar                  | @VERSION@                          | overloadedarmorbar-1.0.4g.jar                              | None                                     |
       | LCHIJA | placebo                              | 1.6.0                              | Placebo-1.12.2-1.6.0.jar                                   | None                                     |
       | LCHIJA | questbook                            | 3.1.1-1.12                         | questbook-3.1.1-1.12.jar                                   | None                                     |
       | LCHIJA | quickleafdecay                       | 1.2.4                              | QuickLeafDecay-MC1.12.1-1.2.4.jar                          | None                                     |
       | LCHIJA | randomtweaks                         | 1.12.2-2.8.3.1                     | randomtweaks-1.12.2-2.8.3.1.jar                            | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCHIJA | resourceloader                       | 1.5.3                              | ResourceLoader-MC1.12.1-1.5.3.jar                          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | bq_standard                          | 3.4.173                            | StandardExpansion-3.4.173.jar                              | None                                     |
       | LCHIJA | surge                                | 2.0.79                             | Surge-1.12.2-2.0.79.jar                                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tipthescales                         | 1.0.4                              | TipTheScales-1.12.2-1.0.4.jar                              | None                                     |
       | LCHIJA | toastcontrol                         | 1.8.1                              | Toast Control-1.12.2-1.8.1.jar                             | None                                     |
       | LCHIJA | tombmanygraves2api                   | 1.12.2-1.0.0                       | tombmanygraves2api-1.12.2-1.0.0.jar                        | None                                     |
       | LCHIJA | tombmanygraves                       | 1.12-4.1.0                         | TombManyGraves-1.12-4.1.0.jar                              | None                                     |
       | LCHIJA | tombmanypluginscosmeticarmorreworked | 1.0.0                              | tombmanypluginscosmeticarmorreworked-1.0.0.jar             | None                                     |
       | LCHIJA | topaddons                            | 1.12.2-1.13.0                      | topaddons-1.12.2-1.13.0.jar                                | None                                     |
       | LCHIJA | torchmaster                          | 1.8.4.84                           | torchmaster_1.12.2-1.8.4.84.jar                            | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | unloader                             | 1.2.0                              | unloader-1.2.0.jar                                         | None                                     |
       | LCHIJA | vanillafix                           | 1.0.10-150                         | VanillaFix-1.0.10-150.jar                                  | None                                     |
       | LCHIJA | wct                                  | 3.12.97                            | WirelessCraftingTerminal-1.12.2-3.12.97.jar                | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | xaerominimap                         | 21.22.5                            | Xaeros_Minimap_21.22.5_Forge_1.12.jar                      | None                                     |
       | LCHIJA | xaeroworldmap                        | 1.18.7                             | XaerosWorldMap_1.18.7_Forge_1.12.jar                       | None                                     |
       | LCHIJA | xtones                               | 1.2.2                              | Xtones-1.2.2.jar                                           | None                                     |
       | LCHIJA | moresoundconfig                      | 1.0.4                              | moresoundconfig-1.0.4.jar                                  | 7904c4e13947c8a616c5f39b26bdeba796500722 |
       | LCHIJA | phosphor-lighting                    | 1.12.2-0.2.7                       | phosphor-forge-mc1.12.2-0.2.7-universal.jar                | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_21.22.5_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      FTBUltimineASM (ftb-ultimine-1202.3.5.jar)
                                        
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      MixinBooter (mixinbooter-2.0.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.18.7_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      MoreSoundConfigCore (moresoundconfig-core-1.0.4.jar)
                                        ichttt.mods.moresoundconfig.asm.MSCTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      LittlePatchingLoader (LittleTiles_v1.5.49_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      LoliASM (loliasm-4.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.2.1-beta.jar)
                                        gregtech.core.GregTechTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  AE2 Version: stable rv6-stable-7-extended_life-v0.52.2 for Forge 14.23.5.2847
  AE2 Integration: IC2:OFF, GTCE:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: AE2 Unofficial Extended Life (appliedenergistics2)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['kaio_ou_cesark3'/2, l='GregorianStruggle', x=450.48, y=58.00, z=706.43]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Syrcan** [comment]
There a fair amount of unexplained crashes with that mod. We are updating the modpack to the latest versions of the mods soon. Hopefully the crashes should go away. Update your issue once you have updated if it still happens.
